services:
  db:
    image: mysql:8.4
    container_name: residencias_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anto
      MYSQL_DATABASE: residencias
      TZ: America/Mexico_City
    ports:
      - "3307:3306"
    volumes:
      - residencias_mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: residencias_app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/residencias?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: anto
      RUTA_ARCHIVOS: /residencias/
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - C:/residencias:/residencias

volumes:
  residencias_mysql_data:
