spring.application.name=Proyecto_residencias
ruta.archivos=${RUTA_ARCHIVOS:${user.home}/residencias}
app.admin.enabled=${APP_ADMIN_ENABLED:true}
app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.password=${APP_ADMIN_PASSWORD:123456}

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/residencias?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:anto}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-swallow-size=-1